/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/lookup/{siret}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup Siret */
        get: operations["lookup_siret_api_v1_companies_lookup__siret__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_api_v1_companies_get"];
        put?: never;
        /** Create Company */
        post: operations["create_company_api_v1_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_api_v1_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/duplicate-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate Check */
        post: operations["duplicate_check_api_v1_vehicles_duplicate_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vehicles */
        get: operations["list_vehicles_api_v1_vehicles_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_vehicles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vehicle */
        get: operations["get_vehicle_api_v1_vehicles__vehicle_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Vehicle */
        patch: operations["patch_vehicle_api_v1_vehicles__vehicle_id__patch"];
        trace?: never;
    };
    "/api/v1/vehicles/{vehicle_id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Allowed Transitions */
        get: operations["get_allowed_transitions_api_v1_vehicles__vehicle_id__transitions_get"];
        put?: never;
        /** Post Transition */
        post: operations["post_transition_api_v1_vehicles__vehicle_id__transitions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Intake Batch */
        post: operations["create_intake_batch_api_v1_intake_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/duplicate-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Duplicate Review
         * @description Un verdict `not_duplicate` est définitif (décision A, étape 5) : la paire n'est plus
         *     jamais reproposée par `run_duplicate_check`. Idempotent : un second arbitrage sur la même
         *     paire met à jour le verdict existant au lieu de violer la contrainte d'unicité.
         */
        post: operations["create_duplicate_review_api_v1_duplicate_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Analytics
         * @description Câblé sur le bouton « Actualiser les indicateurs » du dashboard (plan.md § 3.7-5).
         */
        post: operations["refresh_analytics_api_v1_analytics_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics Status */
        get: operations["analytics_status_api_v1_analytics_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/demo-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Reset Get */
        get: operations["demo_reset_get_api_v1_admin_demo_reset_get"];
        put?: never;
        /** Demo Reset Post */
        post: operations["demo_reset_post_api_v1_admin_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AllowedTransitionsResponse
         * @description Forme figée : objet `{"allowed": [...]}`, pas un tableau nu — laisse la place à des
         *     métadonnées de niveau supérieur (ex. `state`, `state_changed_at`) sans rupture de contrat
         *     si besoin en J2/J3.
         */
        AllowedTransitionsResponse: {
            /** Allowed */
            allowed: components["schemas"]["TransitionOptionRead"][];
        };
        /**
         * CompanyBrief
         * @description Version allégée de `Company`, embarquée dans les réponses véhicule (liste **et** détail)
         *     pour que la colonne/en-tête « Société » soit renseignée sans recharger la ressource
         *     complète (revue § 🟠 « la colonne Société est vide partout »).
         */
        CompanyBrief: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Denomination */
            denomination: string;
            /** Siret */
            siret: string;
        };
        /** CompanyCreate */
        CompanyCreate: {
            /** Siret */
            siret: string;
            /** Denomination */
            denomination: string;
            /** Forme Juridique */
            forme_juridique?: string | null;
            /** Code Naf */
            code_naf?: string | null;
            /** Libelle Naf */
            libelle_naf?: string | null;
            /** Adresse Ligne1 */
            adresse_ligne1: string;
            /** Code Postal */
            code_postal: string;
            /** Commune */
            commune: string;
            /**
             * Pays
             * @default FR
             */
            pays: string;
            /** Tranche Effectif */
            tranche_effectif?: string | null;
            /** Date Creation */
            date_creation?: string | null;
            /** Type Flotte */
            type_flotte: string;
            /** Source Enrichissement */
            source_enrichissement: string;
            /** Contact Nom */
            contact_nom?: string | null;
            /** Contact Telephone */
            contact_telephone?: string | null;
        };
        /** CompanyLookupCompany */
        CompanyLookupCompany: {
            /** Siret */
            siret: string;
            /** Siren */
            siren: string;
            /** Denomination */
            denomination: string;
            /** Forme Juridique */
            forme_juridique?: string | null;
            /** Code Naf */
            code_naf?: string | null;
            /** Libelle Naf */
            libelle_naf?: string | null;
            /** Adresse Ligne1 */
            adresse_ligne1: string;
            /** Code Postal */
            code_postal: string;
            /** Commune */
            commune: string;
            /** Tranche Effectif */
            tranche_effectif?: string | null;
            /** Date Creation */
            date_creation?: string | null;
        };
        /** CompanyLookupResponse */
        CompanyLookupResponse: {
            /** Source */
            source: string;
            /** Stale */
            stale: boolean;
            company: components["schemas"]["CompanyLookupCompany"];
        };
        /** CompanyRead */
        CompanyRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Siren */
            siren: string;
            /** Siret */
            siret: string;
            /** Denomination */
            denomination: string;
            /** Forme Juridique */
            forme_juridique: string | null;
            /** Code Naf */
            code_naf: string | null;
            /** Libelle Naf */
            libelle_naf: string | null;
            /** Adresse Ligne1 */
            adresse_ligne1: string;
            /** Code Postal */
            code_postal: string;
            /** Commune */
            commune: string;
            /** Pays */
            pays: string;
            /** Tranche Effectif */
            tranche_effectif: string | null;
            /** Date Creation */
            date_creation: string | null;
            /** Type Flotte */
            type_flotte: string;
            /** Source Enrichissement */
            source_enrichissement: string;
            /** Enriched At */
            enriched_at: string | null;
            /** Contact Nom */
            contact_nom: string | null;
            /** Contact Telephone */
            contact_telephone: string | null;
            /**
             * Created By Id
             * Format: uuid
             */
            created_by_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DuplicateCandidate
         * @description Fiche existante candidate à un doublon — assez complète pour une comparaison côte à côte
         *     (brief § critères d'acceptation J1) : chaque composante de `features` doit pouvoir être
         *     justifiée par les deux valeurs comparées (correction dev-frontend, jalon J1).
         *
         *     Réservé aux rôles `operatrice`/`administrateur` (seuls appelants de `duplicate-check`, voir
         *     `_WRITE_ROLES` dans `api/v1/vehicles.py`) : ces champs sont déjà visibles par ces rôles sur
         *     n'importe quel véhicule via `GET /vehicles` et `GET /vehicles/{id}` (`scope_vehicles` ne les
         *     restreint pas — plan.md § 3.4), donc cet enrichissement ne crée aucune fuite d'information
         *     au-delà de ce que ces rôles voient déjà.
         */
        DuplicateCandidate: {
            /**
             * Vehicle Id
             * Format: uuid
             */
            vehicle_id: string;
            /** Reference */
            reference: string;
            /** Marque */
            marque: string;
            /** Modele */
            modele: string;
            /** Version */
            version: string | null;
            /** Energie */
            energie: string | null;
            /** Vin */
            vin: string | null;
            /** Immatriculation */
            immatriculation: string | null;
            /** Kilometrage */
            kilometrage: number | null;
            /** Date Mise En Circulation */
            date_mise_en_circulation: string | null;
            /**
             * Date Proposition
             * Format: date
             */
            date_proposition: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** State */
            state: string;
            /** Refus Motif */
            refus_motif: string | null;
            /** Refus Commentaire */
            refus_commentaire: string | null;
            /** Score */
            score: number;
            features: components["schemas"]["DuplicateComponents"];
        };
        /** DuplicateCheckResponse */
        DuplicateCheckResponse: {
            /** Exact */
            exact?: {
                [key: string]: unknown;
            }[];
            /** Probable */
            probable?: components["schemas"]["DuplicateCandidate"][];
            /** Similar */
            similar?: components["schemas"]["DuplicateCandidate"][];
        };
        /** DuplicateComponents */
        DuplicateComponents: {
            /** S Modele */
            s_modele: number;
            /** S Date */
            s_date: number;
            /** S Km */
            s_km: number;
            /** S Energie */
            s_energie: number;
            /** Bonus Terminal */
            bonus_terminal: number;
        };
        /** DuplicateReviewCreate */
        DuplicateReviewCreate: {
            /**
             * Vehicle A Id
             * Format: uuid
             */
            vehicle_a_id: string;
            /**
             * Vehicle B Id
             * Format: uuid
             */
            vehicle_b_id: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "duplicate" | "not_duplicate";
            /** Score */
            score: number;
            /** Features */
            features: {
                [key: string]: unknown;
            };
        };
        /** DuplicateReviewRead */
        DuplicateReviewRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Vehicle A Id
             * Format: uuid
             */
            vehicle_a_id: string;
            /**
             * Vehicle B Id
             * Format: uuid
             */
            vehicle_b_id: string;
            /** Verdict */
            verdict: string;
            /** Score */
            score: number;
            /** Features */
            features: {
                [key: string]: unknown;
            };
            /**
             * Decided By Id
             * Format: uuid
             */
            decided_by_id: string;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntakeBatchCreate */
        IntakeBatchCreate: {
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Label */
            label: string;
        };
        /** IntakeBatchRead */
        IntakeBatchRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Label */
            label: string;
            /**
             * Created By Id
             * Format: uuid
             */
            created_by_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Role */
            role: string;
            /** Telephone */
            telephone?: string | null;
        };
        /** Page[CompanyRead] */
        Page_CompanyRead_: {
            /** Items */
            items: components["schemas"]["CompanyRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[VehicleListItem] */
        Page_VehicleListItem_: {
            /** Items */
            items: components["schemas"]["VehicleListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * TransitionOptionRead
         * @description Une entrée de `GET /vehicles/{id}/transitions` — le front dérive son bouton de ceci sans
         *     connaître l'automate (plan.md § 5.3, revue § 🔴 « enrichis GET /vehicles/{id}/transitions »).
         */
        TransitionOptionRead: {
            /** To State */
            to_state: string;
            /** Label */
            label: string;
            /** Requires Reason */
            requires_reason: boolean;
            /** Requires Payload Fields */
            requires_payload_fields: string[];
        };
        /** TransitionRequest */
        TransitionRequest: {
            /** To State */
            to_state: string;
            /** Reason */
            reason?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VehicleCreate */
        VehicleCreate: {
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Intake Batch Id */
            intake_batch_id?: string | null;
            /** Marque */
            marque: string;
            /** Modele */
            modele: string;
            /** Version */
            version?: string | null;
            /** Energie */
            energie?: string | null;
            /** Boite */
            boite?: string | null;
            /** Couleur */
            couleur?: string | null;
            /** Vin */
            vin?: string | null;
            /** Immatriculation */
            immatriculation?: string | null;
            /** Date Mise En Circulation */
            date_mise_en_circulation?: string | null;
            /** Kilometrage */
            kilometrage?: number | null;
            /**
             * Date Proposition
             * Format: date
             */
            date_proposition: string;
            /** Prix Achat Negocie Cents */
            prix_achat_negocie_cents?: number | null;
            /** Valeur Revente Estimee Cents */
            valeur_revente_estimee_cents?: number | null;
            /**
             * Frais Transport Cents
             * @default 0
             */
            frais_transport_cents: number;
            /** Commentaire */
            commentaire?: string | null;
            /**
             * Force Create
             * @default false
             */
            force_create: boolean;
        };
        /**
         * VehicleListItem
         * @description `GET /vehicles` — sans `state_history` : la liste ne l'affiche pas, et l'embarquer
         *     déclenchait un N+1 (`Vehicle.state_history` en lazy load, un aller-retour par ligne).
         */
        VehicleListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reference */
            reference: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            company: components["schemas"]["CompanyBrief"];
            /** Intake Batch Id */
            intake_batch_id: string | null;
            /** State */
            state: string;
            /** Marque */
            marque: string;
            /** Modele */
            modele: string;
            /** Version */
            version: string | null;
            /** Energie */
            energie: string | null;
            /** Boite */
            boite: string | null;
            /** Couleur */
            couleur: string | null;
            /** Vin */
            vin: string | null;
            /** Immatriculation */
            immatriculation: string | null;
            /** Date Mise En Circulation */
            date_mise_en_circulation: string | null;
            /** Kilometrage */
            kilometrage: number | null;
            /**
             * Date Proposition
             * Format: date
             */
            date_proposition: string;
            /** Prix Achat Negocie Cents */
            prix_achat_negocie_cents: number | null;
            /** Valeur Revente Estimee Cents */
            valeur_revente_estimee_cents: number | null;
            /** Frais Transport Cents */
            frais_transport_cents: number;
            /** Commentaire */
            commentaire: string | null;
            /**
             * Created By Id
             * Format: uuid
             */
            created_by_id: string;
            /** Assigned Driver Id */
            assigned_driver_id: string | null;
            /** Refus Motif */
            refus_motif: string | null;
            /** Refus Commentaire */
            refus_commentaire: string | null;
            /**
             * State Changed At
             * Format: date-time
             */
            state_changed_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * VehiclePatch
         * @description `state` n'apparaît jamais ici — seul `POST /transitions` change l'état (plan.md § 5.3).
         */
        VehiclePatch: {
            /** Marque */
            marque?: string | null;
            /** Modele */
            modele?: string | null;
            /** Version */
            version?: string | null;
            /** Energie */
            energie?: string | null;
            /** Boite */
            boite?: string | null;
            /** Couleur */
            couleur?: string | null;
            /** Vin */
            vin?: string | null;
            /** Immatriculation */
            immatriculation?: string | null;
            /** Date Mise En Circulation */
            date_mise_en_circulation?: string | null;
            /** Kilometrage */
            kilometrage?: number | null;
            /** Date Proposition */
            date_proposition?: string | null;
            /** Prix Achat Negocie Cents */
            prix_achat_negocie_cents?: number | null;
            /** Valeur Revente Estimee Cents */
            valeur_revente_estimee_cents?: number | null;
            /** Frais Transport Cents */
            frais_transport_cents?: number | null;
            /** Commentaire */
            commentaire?: string | null;
            /**
             * Force Update
             * @default false
             */
            force_update: boolean;
        };
        /**
         * VehicleRead
         * @description Fiche détail — `GET /vehicles/{id}`, `POST /vehicles`, `PATCH`, `POST /transitions`.
         *
         *     Frise d'historique d'états, triée chronologiquement — plan.md § 6 vague 4 (front).
         */
        VehicleRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reference */
            reference: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            company: components["schemas"]["CompanyBrief"];
            /** Intake Batch Id */
            intake_batch_id: string | null;
            /** State */
            state: string;
            /** Marque */
            marque: string;
            /** Modele */
            modele: string;
            /** Version */
            version: string | null;
            /** Energie */
            energie: string | null;
            /** Boite */
            boite: string | null;
            /** Couleur */
            couleur: string | null;
            /** Vin */
            vin: string | null;
            /** Immatriculation */
            immatriculation: string | null;
            /** Date Mise En Circulation */
            date_mise_en_circulation: string | null;
            /** Kilometrage */
            kilometrage: number | null;
            /**
             * Date Proposition
             * Format: date
             */
            date_proposition: string;
            /** Prix Achat Negocie Cents */
            prix_achat_negocie_cents: number | null;
            /** Valeur Revente Estimee Cents */
            valeur_revente_estimee_cents: number | null;
            /** Frais Transport Cents */
            frais_transport_cents: number;
            /** Commentaire */
            commentaire: string | null;
            /**
             * Created By Id
             * Format: uuid
             */
            created_by_id: string;
            /** Assigned Driver Id */
            assigned_driver_id: string | null;
            /** Refus Motif */
            refus_motif: string | null;
            /** Refus Commentaire */
            refus_commentaire: string | null;
            /**
             * State Changed At
             * Format: date-time
             */
            state_changed_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** State History */
            state_history?: components["schemas"]["VehicleStateTransitionRead"][];
        };
        /** VehicleStateTransitionRead */
        VehicleStateTransitionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** From State */
            from_state: string | null;
            /** To State */
            to_state: string;
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /** Actor Role */
            actor_role: string;
            /** Reason */
            reason: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    lookup_siret_api_v1_companies_lookup__siret__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                siret: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_api_v1_companies_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CompanyRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_company_api_v1_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_v1_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_check_api_v1_vehicles_duplicate_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vehicles_api_v1_vehicles_get: {
        parameters: {
            query?: {
                state?: string | null;
                company_id?: string | null;
                marque?: string | null;
                created_by_id?: string | null;
                date_proposition_from?: string | null;
                date_proposition_to?: string | null;
                q?: string | null;
                sort?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_VehicleListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_vehicles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vehicle_api_v1_vehicles__vehicle_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_vehicle_api_v1_vehicles__vehicle_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehiclePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_allowed_transitions_api_v1_vehicles__vehicle_id__transitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllowedTransitionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_transition_api_v1_vehicles__vehicle_id__transitions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_intake_batch_api_v1_intake_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeBatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeBatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_duplicate_review_api_v1_duplicate_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateReviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_analytics_api_v1_analytics_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    analytics_status_api_v1_analytics_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    demo_reset_get_api_v1_admin_demo_reset_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_reset_post_api_v1_admin_demo_reset_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
