"""0001_socle

Revision ID: 0001_socle
Revises: 
Create Date: 2026-08-20 12:43:29.009974

Migration initiale — schéma complet des 3 jalons (plan.md § 3.3, décision « (b) »).
Générée par `alembic revision --autogenerate` puis RELUE LIGNE À LIGNE et complétée à la main
(plan.md § 9, risque « migration de schéma ») :
  - index partiels (`postgresql_where`) sur vehicle.vin_normalise / immat_normalisee et sur
    mission (un seul chantier actif) et photo (un angle par inspection en phase contrôle) ;
  - index fonctionnel sur `lower(email)` (app_user) ;
  - colonne `GENERATED ALWAYS AS ... STORED` sur work_order_line.montant_cents ;
  - toutes les contraintes CHECK déclarées dans `__table_args__` des modèles.
Ajout manuel (non détecté par autogenerate, les séquences ne sont pas des objets ORM) :
  - séquence dédiée `vehicle_reference_seq`, consommée par le service de création de véhicule
    pour produire la référence `VH-{année}-{numéro}` (plan.md § 5.1).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_socle'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Séquence dédiée à la référence véhicule (VH-{année}-{numéro}) — ajout manuel.
    op.execute("CREATE SEQUENCE IF NOT EXISTS vehicle_reference_seq START 1")
    # Schéma dérivé (plan.md § 3.7-4) : Alembic ne gère QUE sa création, jamais les vues
    # qu'il contient — celles-ci sont reconstruites à l'identique par `app/analytics/runner.py`.
    op.execute("CREATE SCHEMA IF NOT EXISTS analytics")
    op.create_table('app_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('operatrice', 'chauffeur', 'administrateur', 'atelier')", name=op.f('ck_app_user_role_valide')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user'))
    )
    op.create_index('ix_app_user_role', 'app_user', ['role'], unique=False)
    op.create_index('uq_app_user_email_lower', 'app_user', [sa.text('lower(email)')], unique=True)
    op.create_table('checklist_template',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_template')),
    sa.UniqueConstraint('code', name='uq_checklist_template_code')
    )
    op.create_table('company_lookup_cache',
    sa.Column('siret', sa.String(length=14), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.CheckConstraint("source IN ('api', 'demo')", name=op.f('ck_company_lookup_cache_source_valide')),
    sa.PrimaryKeyConstraint('siret', name=op.f('pk_company_lookup_cache'))
    )
    op.create_index('ix_company_lookup_cache_fetched_at', 'company_lookup_cache', ['fetched_at'], unique=False)
    op.create_table('demo_reset_run',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('seed_version', sa.String(length=50), nullable=False),
    sa.Column('rows_created', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('succes', 'echec')", name=op.f('ck_demo_reset_run_status_valide')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demo_reset_run'))
    )
    op.create_table('lookup_health',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('opened_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider', name=op.f('pk_lookup_health'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], name=op.f('fk_audit_log_actor_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id', sa.text('occurred_at DESC')], unique=False)
    op.create_table('checklist_item_template',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('categorie', sa.String(length=20), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('response_type', sa.String(length=20), nullable=False),
    sa.CheckConstraint("categorie IN ('exterieur', 'interieur', 'mecanique', 'documents', 'securite')", name=op.f('ck_checklist_item_template_categorie_valide')),
    sa.CheckConstraint("response_type IN ('ok_ko', 'note_1_5', 'texte', 'numerique')", name=op.f('ck_checklist_item_template_response_type_valide')),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], name=op.f('fk_checklist_item_template_template_id_checklist_template')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_item_template')),
    sa.UniqueConstraint('template_id', 'code', name='uq_checklist_item_template_template_code')
    )
    op.create_table('company',
    sa.Column('siren', sa.String(length=9), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=False),
    sa.Column('denomination', sa.String(length=255), nullable=False),
    sa.Column('forme_juridique', sa.String(length=255), nullable=True),
    sa.Column('code_naf', sa.String(length=10), nullable=True),
    sa.Column('libelle_naf', sa.String(length=255), nullable=True),
    sa.Column('adresse_ligne1', sa.String(length=255), nullable=False),
    sa.Column('code_postal', sa.String(length=10), nullable=False),
    sa.Column('commune', sa.String(length=255), nullable=False),
    sa.Column('pays', sa.String(length=2), server_default='FR', nullable=False),
    sa.Column('tranche_effectif', sa.String(length=10), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('type_flotte', sa.String(length=20), nullable=False),
    sa.Column('source_enrichissement', sa.String(length=10), nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_nom', sa.String(length=255), nullable=True),
    sa.Column('contact_telephone', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("siret ~ '^[0-9]{14}$'", name=op.f('ck_company_siret_format')),
    sa.CheckConstraint("source_enrichissement IN ('api', 'cache', 'demo', 'manuel')", name=op.f('ck_company_source_enrichissement_valide')),
    sa.CheckConstraint("type_flotte IN ('taxi', 'ambulance', 'transport', 'auto_ecole', 'location', 'autre')", name=op.f('ck_company_type_flotte_valide')),
    sa.CheckConstraint('siren = left(siret, 9)', name=op.f('ck_company_siren_coherent_avec_siret')),
    sa.ForeignKeyConstraint(['created_by_id'], ['app_user.id'], name=op.f('fk_company_created_by_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company')),
    sa.UniqueConstraint('siret', name='uq_company_siret')
    )
    op.create_index('ix_company_denomination', 'company', ['denomination'], unique=False)
    op.create_index('ix_company_siren', 'company', ['siren'], unique=False)
    op.create_index('ix_company_type_flotte', 'company', ['type_flotte'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('corps', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_notification_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index('ix_notification_user_created', 'notification', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_table('push_subscription',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_push_subscription_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscription')),
    sa.UniqueConstraint('endpoint', name='uq_push_subscription_endpoint')
    )
    op.create_table('intake_batch',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_intake_batch_company_id_company')),
    sa.ForeignKeyConstraint(['created_by_id'], ['app_user.id'], name=op.f('fk_intake_batch_created_by_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intake_batch'))
    )
    op.create_index('ix_intake_batch_company_id', 'intake_batch', ['company_id'], unique=False)
    op.create_table('vehicle',
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('intake_batch_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('marque', sa.String(length=100), nullable=False),
    sa.Column('modele', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('modele_normalise', sa.String(length=255), nullable=True),
    sa.Column('energie', sa.String(length=20), nullable=True),
    sa.Column('boite', sa.String(length=20), nullable=True),
    sa.Column('couleur', sa.String(length=50), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('vin_normalise', sa.String(length=17), nullable=True),
    sa.Column('immatriculation', sa.String(length=20), nullable=True),
    sa.Column('immat_normalisee', sa.String(length=10), nullable=True),
    sa.Column('date_mise_en_circulation', sa.Date(), nullable=True),
    sa.Column('kilometrage', sa.Integer(), nullable=True),
    sa.Column('date_proposition', sa.Date(), nullable=False),
    sa.Column('prix_achat_negocie_cents', sa.Integer(), nullable=True),
    sa.Column('valeur_revente_estimee_cents', sa.Integer(), nullable=True),
    sa.Column('frais_transport_cents', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_driver_id', sa.Uuid(), nullable=True),
    sa.Column('refus_motif', sa.String(length=20), nullable=True),
    sa.Column('refus_commentaire', sa.Text(), nullable=True),
    sa.Column('state_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("boite IS NULL OR boite IN ('manuelle', 'automatique')", name=op.f('ck_vehicle_boite_valide')),
    sa.CheckConstraint("energie IS NULL OR energie IN ('essence', 'diesel', 'hybride', 'electrique', 'gpl', 'autre')", name=op.f('ck_vehicle_energie_valide')),
    sa.CheckConstraint("refus_motif IS NULL OR refus_motif IN ('etat_mecanique', 'carrosserie', 'kilometrage', 'prix', 'vendeur_retracte', 'autre')", name=op.f('ck_vehicle_refus_motif_valide')),
    sa.CheckConstraint("state <> 'REFUSE' OR refus_motif IS NOT NULL", name=op.f('ck_vehicle_refus_motif_requis_si_refuse')),
    sa.CheckConstraint("state IN ('BROUILLON', 'A_PLANIFIER', 'AFFECTE', 'RDV_PLANIFIE', 'CONTROLE_EN_COURS', 'TRAVAUX_REQUIS', 'TRAVAUX_EN_COURS', 'TRAVAUX_TERMINES', 'ACHAT_VALIDE', 'REFUSE', 'ANNULE')", name=op.f('ck_vehicle_state_valide')),
    sa.CheckConstraint("vin_normalise IS NULL OR vin_normalise ~ '^[A-HJ-NPR-Z0-9]{17}$'", name=op.f('ck_vehicle_vin_normalise_format')),
    sa.CheckConstraint('frais_transport_cents >= 0', name=op.f('ck_vehicle_frais_transport_positif')),
    sa.CheckConstraint('kilometrage IS NULL OR kilometrage >= 0', name=op.f('ck_vehicle_kilometrage_positif')),
    sa.CheckConstraint('prix_achat_negocie_cents IS NULL OR prix_achat_negocie_cents >= 0', name=op.f('ck_vehicle_prix_achat_positif')),
    sa.ForeignKeyConstraint(['assigned_driver_id'], ['app_user.id'], name=op.f('fk_vehicle_assigned_driver_id_app_user')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_vehicle_company_id_company')),
    sa.ForeignKeyConstraint(['created_by_id'], ['app_user.id'], name=op.f('fk_vehicle_created_by_id_app_user')),
    sa.ForeignKeyConstraint(['intake_batch_id'], ['intake_batch.id'], name=op.f('fk_vehicle_intake_batch_id_intake_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle')),
    sa.UniqueConstraint('reference', name='uq_vehicle_reference')
    )
    op.create_index('ix_vehicle_assigned_driver_state', 'vehicle', ['assigned_driver_id', 'state'], unique=False)
    op.create_index('ix_vehicle_company_date', 'vehicle', ['company_id', 'date_proposition'], unique=False)
    op.create_index('ix_vehicle_created_by_created_at', 'vehicle', ['created_by_id', 'created_at'], unique=False)
    op.create_index('ix_vehicle_date_proposition', 'vehicle', ['date_proposition'], unique=False)
    op.create_index('ix_vehicle_state', 'vehicle', ['state'], unique=False)
    op.create_index('uq_vehicle_immat_normalisee', 'vehicle', ['immat_normalisee'], unique=True, postgresql_where=sa.text('immat_normalisee IS NOT NULL'))
    op.create_index('uq_vehicle_vin_normalise', 'vehicle', ['vin_normalise'], unique=True, postgresql_where=sa.text('vin_normalise IS NOT NULL'))
    op.create_table('duplicate_review',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_a_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_b_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decided_by_id', sa.Uuid(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verdict IN ('duplicate', 'not_duplicate')", name=op.f('ck_duplicate_review_verdict_valide')),
    sa.CheckConstraint('vehicle_a_id < vehicle_b_id', name=op.f('ck_duplicate_review_paire_canonique')),
    sa.ForeignKeyConstraint(['decided_by_id'], ['app_user.id'], name=op.f('fk_duplicate_review_decided_by_id_app_user')),
    sa.ForeignKeyConstraint(['vehicle_a_id'], ['vehicle.id'], name=op.f('fk_duplicate_review_vehicle_a_id_vehicle')),
    sa.ForeignKeyConstraint(['vehicle_b_id'], ['vehicle.id'], name=op.f('fk_duplicate_review_vehicle_b_id_vehicle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplicate_review')),
    sa.UniqueConstraint('vehicle_a_id', 'vehicle_b_id', name='uq_duplicate_review_paire')
    )
    op.create_table('mission',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('rdv_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rdv_adresse', sa.String(length=255), nullable=True),
    sa.Column('rdv_contact_nom', sa.String(length=255), nullable=True),
    sa.Column('rdv_contact_telephone', sa.String(length=20), nullable=True),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("state IN ('affectee', 'acceptee', 'rdv_planifie', 'en_cours', 'terminee', 'annulee')", name=op.f('ck_mission_state_valide')),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['app_user.id'], name=op.f('fk_mission_assigned_by_id_app_user')),
    sa.ForeignKeyConstraint(['driver_id'], ['app_user.id'], name=op.f('fk_mission_driver_id_app_user')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('fk_mission_vehicle_id_vehicle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission'))
    )
    op.create_index('ix_mission_driver_state', 'mission', ['driver_id', 'state'], unique=False)
    op.create_index('uq_mission_vehicle_active', 'mission', ['vehicle_id'], unique=True, postgresql_where=sa.text("state NOT IN ('terminee', 'annulee')"))
    op.create_table('vehicle_cost',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('montant_cents', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('transport', 'carburant', 'administratif', 'remise_en_etat_externe', 'autre')", name=op.f('ck_vehicle_cost_type_valide')),
    sa.ForeignKeyConstraint(['created_by_id'], ['app_user.id'], name=op.f('fk_vehicle_cost_created_by_id_app_user')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('fk_vehicle_cost_vehicle_id_vehicle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_cost'))
    )
    op.create_table('vehicle_state_transition',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('from_state', sa.String(length=20), nullable=True),
    sa.Column('to_state', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], name=op.f('fk_vehicle_state_transition_actor_id_app_user')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('fk_vehicle_state_transition_vehicle_id_vehicle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_state_transition'))
    )
    op.create_index('ix_vst_vehicle_occurred', 'vehicle_state_transition', ['vehicle_id', 'occurred_at'], unique=False)
    op.create_table('work_order',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('montant_estime_cents', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commentaire_atelier', sa.Text(), nullable=True),
    sa.CheckConstraint("state IN ('demande', 'en_cours', 'termine', 'annule')", name=op.f('ck_work_order_state_valide')),
    sa.CheckConstraint("type IN ('carrosserie', 'mecanique', 'nettoyage', 'pneumatiques', 'autre')", name=op.f('ck_work_order_type_valide')),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['app_user.id'], name=op.f('fk_work_order_assigned_to_id_app_user')),
    sa.ForeignKeyConstraint(['created_by_id'], ['app_user.id'], name=op.f('fk_work_order_created_by_id_app_user')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('fk_work_order_vehicle_id_vehicle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order'))
    )
    op.create_index('ix_work_order_state_assignee', 'work_order', ['state', 'assigned_to_id'], unique=False)
    op.create_index('ix_work_order_vehicle', 'work_order', ['vehicle_id'], unique=False)
    op.create_table('inspection',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('client_uuid', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kilometrage_releve', sa.Integer(), nullable=True),
    sa.Column('etat_general', sa.String(length=10), nullable=True),
    sa.Column('conclusion', sa.String(length=20), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("conclusion IS NULL OR conclusion IN ('achat_direct', 'travaux_requis', 'refus')", name=op.f('ck_inspection_conclusion_valide')),
    sa.CheckConstraint("etat_general IS NULL OR etat_general IN ('bon', 'moyen', 'mauvais')", name=op.f('ck_inspection_etat_general_valide')),
    sa.ForeignKeyConstraint(['driver_id'], ['app_user.id'], name=op.f('fk_inspection_driver_id_app_user')),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], name=op.f('fk_inspection_mission_id_mission')),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], name=op.f('fk_inspection_template_id_checklist_template')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('fk_inspection_vehicle_id_vehicle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection')),
    sa.UniqueConstraint('client_uuid', name='uq_inspection_client_uuid')
    )
    op.create_index('ix_inspection_vehicle', 'inspection', ['vehicle_id'], unique=False)
    op.create_table('work_order_line',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('categorie', sa.String(length=20), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prix_unitaire_cents', sa.Integer(), nullable=False),
    sa.Column('montant_cents', sa.Integer(), sa.Computed('round(quantite * prix_unitaire_cents)::integer', persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("categorie IN ('piece', 'main_oeuvre', 'sous_traitance', 'consommable')", name=op.f('ck_work_order_line_categorie_valide')),
    sa.CheckConstraint('prix_unitaire_cents >= 0', name=op.f('ck_work_order_line_prix_unitaire_positif')),
    sa.CheckConstraint('quantite > 0', name=op.f('ck_work_order_line_quantite_positive')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], name=op.f('fk_work_order_line_work_order_id_work_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_line'))
    )
    op.create_table('photo',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('inspection_id', sa.Uuid(), nullable=True),
    sa.Column('work_order_id', sa.Uuid(), nullable=True),
    sa.Column('angle', sa.String(length=40), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('storage_bucket', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('client_uuid', sa.Uuid(), nullable=False),
    sa.Column('upload_state', sa.String(length=20), nullable=False),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("angle IN ('face_avant', 'trois_quarts_avant_gauche', 'profil_gauche', 'trois_quarts_arriere_gauche', 'face_arriere', 'trois_quarts_arriere_droit', 'profil_droit', 'trois_quarts_avant_droit', 'interieur_avant', 'interieur_arriere', 'coffre', 'compteur', 'defaut')", name=op.f('ck_photo_angle_valide')),
    sa.CheckConstraint("phase IN ('controle', 'avant_travaux', 'apres_travaux')", name=op.f('ck_photo_phase_valide')),
    sa.CheckConstraint("upload_state IN ('en_attente', 'envoyee', 'echouee')", name=op.f('ck_photo_upload_state_valide')),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], name=op.f('fk_photo_inspection_id_inspection')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['app_user.id'], name=op.f('fk_photo_uploaded_by_id_app_user')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name=op.f('fk_photo_vehicle_id_vehicle')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_order.id'], name=op.f('fk_photo_work_order_id_work_order')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo')),
    sa.UniqueConstraint('client_uuid', name='uq_photo_client_uuid'),
    sa.UniqueConstraint('storage_key', name='uq_photo_storage_key')
    )
    op.create_index('ix_photo_vehicle_phase', 'photo', ['vehicle_id', 'phase'], unique=False)
    op.create_index('uq_photo_inspection_angle_controle', 'photo', ['inspection_id', 'angle'], unique=True, postgresql_where=sa.text("phase = 'controle' AND angle <> 'defaut'"))
    op.create_table('inspection_item',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('item_template_id', sa.Uuid(), nullable=False),
    sa.Column('valeur_bool', sa.Boolean(), nullable=True),
    sa.Column('valeur_note', sa.Integer(), nullable=True),
    sa.Column('valeur_texte', sa.Text(), nullable=True),
    sa.Column('valeur_num', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('photo_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], name=op.f('fk_inspection_item_inspection_id_inspection')),
    sa.ForeignKeyConstraint(['item_template_id'], ['checklist_item_template.id'], name=op.f('fk_inspection_item_item_template_id_checklist_item_template')),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], name=op.f('fk_inspection_item_photo_id_photo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_item')),
    sa.UniqueConstraint('inspection_id', 'item_template_id', name='uq_inspection_item_inspection_template')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Schéma dérivé (plan.md § 3.7-4), hors Alembic : ses vues dépendent des tables
    # opérationnelles et doivent disparaître AVANT elles, sans quoi Postgres refuse le DROP
    # (DependentObjectsStillExist) — piège constaté à la relecture manuelle de ce downgrade.
    op.execute("DROP SCHEMA IF EXISTS analytics CASCADE")
    op.drop_table('inspection_item')
    op.drop_index('uq_photo_inspection_angle_controle', table_name='photo', postgresql_where=sa.text("phase = 'controle' AND angle <> 'defaut'"))
    op.drop_index('ix_photo_vehicle_phase', table_name='photo')
    op.drop_table('photo')
    op.drop_table('work_order_line')
    op.drop_index('ix_inspection_vehicle', table_name='inspection')
    op.drop_table('inspection')
    op.drop_index('ix_work_order_vehicle', table_name='work_order')
    op.drop_index('ix_work_order_state_assignee', table_name='work_order')
    op.drop_table('work_order')
    op.drop_index('ix_vst_vehicle_occurred', table_name='vehicle_state_transition')
    op.drop_table('vehicle_state_transition')
    op.drop_table('vehicle_cost')
    op.drop_index('uq_mission_vehicle_active', table_name='mission', postgresql_where=sa.text("state NOT IN ('terminee', 'annulee')"))
    op.drop_index('ix_mission_driver_state', table_name='mission')
    op.drop_table('mission')
    op.drop_table('duplicate_review')
    op.drop_index('uq_vehicle_vin_normalise', table_name='vehicle', postgresql_where=sa.text('vin_normalise IS NOT NULL'))
    op.drop_index('uq_vehicle_immat_normalisee', table_name='vehicle', postgresql_where=sa.text('immat_normalisee IS NOT NULL'))
    op.drop_index('ix_vehicle_state', table_name='vehicle')
    op.drop_index('ix_vehicle_date_proposition', table_name='vehicle')
    op.drop_index('ix_vehicle_created_by_created_at', table_name='vehicle')
    op.drop_index('ix_vehicle_company_date', table_name='vehicle')
    op.drop_index('ix_vehicle_assigned_driver_state', table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index('ix_intake_batch_company_id', table_name='intake_batch')
    op.drop_table('intake_batch')
    op.drop_table('push_subscription')
    op.drop_index('ix_notification_user_created', table_name='notification')
    op.drop_table('notification')
    op.drop_index('ix_company_type_flotte', table_name='company')
    op.drop_index('ix_company_siren', table_name='company')
    op.drop_index('ix_company_denomination', table_name='company')
    op.drop_table('company')
    op.drop_table('checklist_item_template')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('lookup_health')
    op.drop_table('demo_reset_run')
    op.drop_index('ix_company_lookup_cache_fetched_at', table_name='company_lookup_cache')
    op.drop_table('company_lookup_cache')
    op.drop_table('checklist_template')
    op.drop_index('uq_app_user_email_lower', table_name='app_user')
    op.drop_index('ix_app_user_role', table_name='app_user')
    op.drop_table('app_user')
    op.execute("DROP SEQUENCE IF EXISTS vehicle_reference_seq")
    # ### end Alembic commands ###
