"""0002_analytics_refresh_log

Revision ID: 0002_analytics_refresh_log
Revises: 0001_socle
Create Date: 2026-08-20 13:13:07.650082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002_analytics_refresh_log"
down_revision: Union[str, None] = "0001_socle"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_log",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("mart_name", sa.String(length=100), nullable=False),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('succes', 'echec')", name=op.f("ck_refresh_log_status_valide")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_log")),
        schema="analytics",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("refresh_log", schema="analytics")
    # ### end Alembic commands ###
