"""0003_inspection_mission_unique

Revision ID: 0003_inspection_mission_unique
Revises: 0002_analytics_refresh_log
Create Date: 2026-08-20 00:00:00.000000

Corrige review-j2.md § 5 (recharger l'écran de contrôle juste après soumission créait une
seconde `inspection` pour le même véhicule/la même mission, le véhicule restant en
`CONTROLE_EN_COURS` jusqu'à la transition suivante). Le garde-fou applicatif
(`app/services/inspections.py::get_or_create_inspection`, qui renvoie désormais l'inspection
existante de la mission plutôt que d'en ouvrir une seconde) ferme la fenêtre en usage normal,
mais ne protège pas contre deux requêtes `POST /inspections` concurrentes avec des `client_uuid`
distincts (même chauffeur, deux onglets, ou rejeu réseau agressif) : les deux passeraient la
lecture "existe-t-il déjà une inspection pour cette mission ?" avant qu'aucune n'ait inséré la
sienne. D'où cette contrainte au niveau base.

Contrainte **totale**, pas un index partiel : à la différence de `photo` (angles répétables
selon la phase, cf. `uq_photo_inspection_angle_controle`), il n'existe aucun cas légitime de
deux inspections pour la même mission, quel que soit son état — `RDV_PLANIFIE →
CONTROLE_EN_COURS` est l'unique transition qui crée une `inspection` (plan.md § 5.3), jamais
rejouée pour une même mission.

Nettoyage de données AVANT la contrainte (autogenerate ne le fait jamais, ajouté à la main) :
la base de dev/démo peut déjà porter des doublons produits par le bug ci-dessus (observé en
local : 29 missions à 2 lignes `inspection` chacune, issues d'exécutions e2e répétées avant
correctif). On conserve, par mission, la première inspection créée (`started_at` le plus
ancien — c'est celle que le correctif applicatif aurait renvoyée) et on supprime les suivantes
ainsi que leurs `inspection_item`/`photo` orphelins (aucun `ON DELETE CASCADE` sur ces FK,
cf. `0001_socle`). Les octets déjà écrits sur disque pour les photos supprimées deviennent
orphelins : sans conséquence pratique, même traitement que les écritures avortées documenté
dans `app/services/photos.py` (purgés au reset nocturne, `runtime/` entièrement vidé).
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_inspection_mission_unique"
down_revision: Union[str, None] = "0002_analytics_refresh_log"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_LOSERS_CTE = """
    WITH losers AS (
        SELECT id
        FROM (
            SELECT id, mission_id,
                   row_number() OVER (
                       PARTITION BY mission_id ORDER BY started_at ASC, id ASC
                   ) AS rn
            FROM inspection
        ) ranked
        WHERE rn > 1
    )
"""


def upgrade() -> None:
    # ### nettoyage manuel des doublons pré-existants, PUIS commandes générées par Alembic ###
    op.execute(_LOSERS_CTE + "DELETE FROM photo WHERE inspection_id IN (SELECT id FROM losers)")
    op.execute(
        _LOSERS_CTE + "DELETE FROM inspection_item WHERE inspection_id IN (SELECT id FROM losers)"
    )
    op.execute(_LOSERS_CTE + "DELETE FROM inspection WHERE id IN (SELECT id FROM losers)")

    op.create_unique_constraint("uq_inspection_mission", "inspection", ["mission_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_inspection_mission", "inspection", type_="unique")
    # ### end Alembic commands ###
    # Note : le nettoyage de données ci-dessus n'est pas réversible (les inspections
    # dupliquées supprimées ne peuvent pas être reconstituées) — assumé, il s'agit de
    # doublons produits par un bug, jamais d'une donnée légitime.
